name: pantryfox
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^2.3.3

  path_provider: ^1.5.1
  url_launcher: ^5.4.1
  flutter_slidable: ^0.5.4
  barcode_scan: ^3.0.1
  ## Fancy loading wheel animations
  flutter_spinkit: ^4.1.1+1
  flushbar: ^1.10.4
  uuid: ^2.2.0

  flutter_bloc: ^5.0.1
  form_bloc: ^0.15.0
  flutter_form_bloc: ^0.15.0
  equatable: ^1.0.1
  device_info: ^0.4.2+4

  encrypt: ^3.3.1

  # Required as of
  firebase_core: ^0.5.0
  # Aug 17 2020
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  cloud_functions: ^0.6.0

  # Flutter Ads
  flutter_google_ad_manager: ^0.11.1

  # In app purchases
  in_app_purchase: ^0.3.4+5

  # cached images
  # cached_network_image: ^2.2.0+1

  http: 0.12.1
  sqflite:
  jaguar_query_sqflite: ^2.2.11
  jaguar_orm: ^2.2.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  # ios and android icons
  flutter_launcher_icons: "^0.7.3"

  flutter_test:
    sdk: flutter
  test: ^1.9.4
  bloc_test: ^6.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fox.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # For translation to work on iOS you need to add supported locales to ios/Runner/Info.plist as described here:
    # https://flutter.dev/docs/development/accessibility-and-localization/internationalization#specifying-supportedlocales
    - assets/langs/


flutter_localizations:
  sdk: flutter
